# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Astro-SolarParallax
version:      0.03
version_from: lib/Astro/SolarParallax.pm
installdirs:  site
requires:
    Math::Trig:                    0
    Time::Piece:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
